Anpassungen am Design und Position der Anhänge
rheinertleon/LaTeX-Template pull request #1
Opened 2024-03-21 15:20 UTC by akarrenbauer

2024-03-31 11:13 UTC, rheinertleon requested changes
Hallo Herr Karrenbauer,

danke für Ihr Interesse am und Ihren Beitrag zum Projekt. Ist immer noch Herr Hofbauer der Ansprechpartner auf ASW Seite bezüglich Vorlagen?
Ihre Änderungen sehen soweit gut aus. Eine Kleinigkeit sollten Sie noch verbessern bevor ich den PR merge. Ich gehe mal davon aus, dass die Ändungen der Reihenfolge der Bilder im Titelblatt und der Reihenfolge von Literaturverzeichnis und Anhang mit dem aktuellen Betreuer/Verantwortlichen abgesprochen sind.

2024-03-31 11:13 UTC, rheinertleon commented on main.tex
> +
Der Anhang sollte die gleiche Textdichte aufweisen wie der Haupttext. Also wäre ein `\setstretch{1.2}` noch wichtig.

2024-03-31 11:13 UTC, rheinertleon commented on environment/config.tex
> +\newcommand{\varTitlepage}{environment/titlepage}
Eher aus Interesse: Kommt die Alternativ-Titlepage nicht mehr so gut an? Meine Bachelorarbeit hatte tatsächlich dieses genutzt.

2024-04-05 17:28 UTC, akarrenbauer commented on main.tex
> +
Das stimmt. Tatsächlich beinhaltet die Vorgabe des Leitfadens nur 1,2- oder 1,3-fache Zeilenabstände. Deshalb habe ich die Umstellung auf 1,1-fachen Zeilenabstand nun entfernt.

2024-04-05 17:31 UTC, akarrenbauer commented on environment/config.tex
> +\newcommand{\varTitlepage}{environment/titlepage}
Nach interner Rücksprache wird den Studierenden freigestellt, welches Deckblatt sie verwenden, solange alle Angaben aus dem Leitfaden enthalten sind, das aktuelle Logo verwendet wird und der nun obsolete Begriff "Berufsakademie" nicht mehr auftaucht. Die Default-Variante sollte wegen der Ähnlichkeit zur Word-Vorlage die klassische sein.

2024-04-05 17:33 UTC, akarrenbauer commented on environment/config.tex
> +\newcommand{\varTitlepage}{environment/titlepage}
Außerdem wird der Name nun nicht mehr mit \textsc gesetzt, da dies zu Abweichungen bei Namen mit ß führen könnte.

2024-04-05 17:39 UTC, akarrenbauer commented
Die Änderung bzgl. Reihenfolge der Logos und die Position des Anhangs sind ASW-intern abgesprochen.

2024-04-07 09:48 UTC, rheinertleon commented
Entschuldigen Sie meine initiale Navität; bislang habe ich Fragen und Anmerkungen zum Projekt lediglich von Studenten erhalten. Mir war daher nicht bewusst, dass das Projekt nun als anerkannte Vorlage dient und Sie der neue Ansprechpartner sind. Ich nehme Sie gerne als Maintainer des Projekts auf.

Nur noch eine Anmerkung zum Code selbst: Der Zeilenabstand wurde von mir bewusst auf `\setstretch{1.1}`, sprich entgegen des Wertes der Vorlage gesetzt. Die Basis davon war, dass ich die "Menge" an Text verglichen habe. Wenn also bei Word der Zeilenabstand auf 1.2 gesetzt ist und bei Latex auf 1.1, dann sind die Seiten exakt gleich gefüllt. Sonst müsste man in Latex weniger Text schreiben, um auf die Mindestseitenzahl zu kommen. Die entgültige Entscheidung darüber ist aber Ihnen überlassen - insbesondere sollte man es auch wieder testen, um sicher zu sein.

2024-04-07 11:45 UTC, akarrenbauer commented
Kein Problem, vielen Dank für die Einladung. Kann es eventuell sein, dass Sie meine begleitenden E-Mails an die auf der Überblickseite angegebene GMail-Adresse gar nicht bekommen haben?

2024-04-08 06:54 UTC, rheinertleon commented
Tatsächlich ist die E-Mail im Spam gelandet. Die ursprünglichen Anpassungen werden dort ja gut erklärt. Es ist also nur noch offen, ob der Zeilenabstand bei 1.1 bleiben sollte, um den angezielten 1.2 aus der Word-Vorlage näher zu kommen, oder ob 1.2 sinnvoller ist (in diesem Fall wäre es dennoch sinnvoll den Wert explizit zu setzen?),

2024-04-09 15:33 UTC, akarrenbauer commented
Der Zeilenabstand sollte durchgehend auf 1.2 gesetzt werden, da eh nur die Seitenzahl des Texteils zählt (also ohne Literaturliste und potenzielle Anhänge). Das kann gerne explizit für jeden Bereich gesetzt werden.

2024-04-09 23:25 UTC, merged